DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS FINGERPRINT;
DROP TABLE IF EXISTS BLOCKCONF;

CREATE TABLE MESSAGES
  (
     SOURCEID      VARCHAR(255),
     MESSAGE       VARCHAR(255),
     MESSAGEDIGEST BINARY(128),
     PARENTDIGEST  BINARY(128),
     IPADDRESS     INT,
     TIMESTAMP     BIGINT,
     PUBLICKEY     BINARY(1024),
     SIGNATURE     BINARY(1024),
     PRIMARY KEY(SOURCEID, MESSAGEDIGEST, TIMESTAMP)
  );

CREATE TABLE FINGERPRINT
  (
     PUBLICKEY     VARCHAR(255),
     IPADDRESS     INT,
     COUNT         INT,
     TSSTART       BIGINT,
     TSEND         BIGINT,
     PRIMARY KEY(PUBLICKEY)
  );

CREATE TABLE BLOCKCONF
  (
     TIMESTAMP     BIGINT,
     COUNT         INT,
     PRIMARY KEY(TIMESTAMP)
  );
